# Generated by Django 3.0.5 on 2020-09-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('water_line_compatible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CoffeePod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('coffee_flavor', models.CharField(max_length=100)),
                ('pack_size', models.SmallIntegerField()),
            ],
        ),
    ]
